FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy producer code
COPY src/producer /app/producer

CMD ["python", "-u", "producer/binance_producer.py"]